collections:
  gists:
    output: true

defaults:
  - scope:
      path: ""
      type: gists
    values:
      layout: gist
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default
