collections:
  articles:
    output: true
  gists:
    output: true

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article
  - scope:
      path: ""
      type: gists
    values:
      layout: gist
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default
